APP-21 Added: net.jini.lookup.JoinManager.level = OFF
So the following messages wont be shown to users. In case these still needs to be showed, thsi property can be modified:

Jun 29, 2006 1:02:39 PM net.jini.lookup.JoinManager$ProxyReg fail
INFO: JoinManager - failure
java.lang.IllegalArgumentException: argument type mismatch

svn path=/trunk/gigaspaces/; revision=9219


Former-commit-id: 8be84e7972149f39297de725834ea80e2606a23b