Fix java.lang.NoClassDefFoundError: org/jini/rio/qos/InetAddressFactory caused by latest changes to "remove using hostname, use BootUtil.getHostAddress instead to correlate with all the places we reference the host address"
No need to use this factory class, use InetAddress directly.

svn path=/trunk/gigaspaces/; revision=59728


Former-commit-id: 1488a67fd6969132963e1d6af5c4e8f54830095d