QA-621
increased renewal duration of transaction to 10 seconds instead of 5, to avoid
net.jini.core.transaction.TransactionException: LocalTransactionManager: transaction 3 not active.

svn path=/trunk/gigaspaces/; revision=11490


Former-commit-id: a21b875eef4fd916914d2bcad6050b1e07a1ad5b