GS-4655 GS-4501 revert back to ThreadPoolExecutor instead of WorkingGroup - for some reason we get a NoClassDefFoundError, which denies the UI from handling events.
svn path=/trunk/gigaspaces/; revision=27175


Former-commit-id: 54813f571b9554c1e4015d929256c63348d96a2a