GS-2558
NotSerializableException: com.j_spaces.jms.GSSessionImpl when a JMS message is serialized. We couldn't reproduce the problem but the message's session member was declared as transient.

svn path=/trunk/gigaspaces/; revision=17112


Former-commit-id: e2dbee34f8272d423d9845b4353635b3cfa20632