GS-8195: NotSerializableException is thrown instead of root cause of ReadByIds, TakeByIds and WriteMultiple exceptions.
java.io.NotSerializableException: org.openspaces.core.exception.DefaultExceptionTranslator is thrown when trying to serialize a result holding the non-serializable translator.

svn path=/trunk/openspaces/; revision=74132


Former-commit-id: efa41cba17931f12658ffffdf4edc7ab2503bc3b